### ISSUE TITLE
Version problem with MCServerUpdater for 1.20.4

### ISSUE THREAD

**Issue by x9nico** [DivineMC/DivineMC#13]
### Expected behavior

It should update to the latest version by using MCServerUpdater.

### Observed/Actual behavior

When MCServerUpdater tries to get the latest version of DivineMC, it don't want update to the latest version (@HSGamer told me to ask to you instead).
=> https://github.com/HSGamer/MCServerUpdater/issues/8
 

### Steps/models to reproduce

- Use MCServerUpdater (https://github.com/HSGamer/MCServerUpdater/ ) to update DivineMC 1.20.4 to latest build : 
 `java -jar MCServerUpdater.jar --project divinemc --output spigot.jar`
- make /version command

### DivineMC version

> ver
[19:37:08 INFO]: Checking version, please wait...
[19:37:08 INFO]: Current: git-DivineMC-"816236f" (MC: 1.20.4)*
Previous: git-DivineMC-"6f72fa0" (MC: 1.20.4)
* You are 1 version(s) behind
Download the new version at: https://github.com/DivineMC/DivineMC/releases/latest

### Agreements

- [X] I am running the latest version of DivineMC from [here](https://github.com/DivineMC/DivineMC/releases/latest).
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by DivineMC.

### Other

I'm asking to you because @HSGamer told me to ask to you instead.
Here is the origin from his message => https://github.com/HSGamer/MCServerUpdater/issues/8

**Comment by NONPLAYT** [comment]
Thank you for issue, I will check it today.

Do you have any logs from MCUpdater?

**Comment by x9nico** [comment]
> Thank you for issue, I will check it today.
> 
> Do you have any logs from MCServerUpdater?

I already set somes screens of logs from the MCserverUpdater issue => https://github.com/HSGamer/MCServerUpdater/issues/8

**Comment by NONPLAYT** [comment]
hello, I just tested this and I have the latest version downloaded. if he writes that there is a new version, but it cannot be downloaded, then there is a new commit, but there is no build
