### ISSUE TITLE
Crash using FansyHologram plugin

### ISSUE THREAD

**Issue by MennoGamed** [DivineMC/DivineMC#14]
### Expected behavior

What I expect is that this plugin should just work and be able to start.

### Observed/Actual behavior

That as soon as I try to use the plugin, it crashes and gives this error: https://pastebin.com/tbcNQnRz

### Steps/models to reproduce

To reproduce this error, download the latest version of DivineMC and the plugin.
- https://hangar.papermc.io/Oliver/FancyHolograms

Use a random command, I use as an example /hologram create text test. After this, you immediately get the error in the console.

### DivineMC version

Current: 1.20.6-DEV-d80347a (MC: 1.20.6)*
* You are running the latest version

### Agreements

- [X] I am running the latest version of DivineMC from [here](https://github.com/DivineMC/DivineMC/releases/latest).
- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] My version of Minecraft is supported by DivineMC.

### Other

I tested the plugin with the same version on both Paper and Purpur to ensure that the problem was not already there or with the plugin itself. In all these cases, everything works as it should, from which I conclude that DivineMC is causing the problem.

**Comment by NONPLAYT** [comment]
I checked, there is such an error. Looking for solutions

**Comment by NONPLAYT** [comment]
Hello, could you try downloading the paperclip mojmap jar? I think it will fix this problem
